INSERT INTO rapocore_author VALUES ("1","Aamer","Hussein","","Before database");;
INSERT INTO rapocore_author VALUES ("2","Advaita","Kala","","Before database");;
INSERT INTO rapocore_author VALUES ("3","Agatha","Christie","","Before database");;
INSERT INTO rapocore_author VALUES ("4","Amish","Tripathi","","Before database");;
INSERT INTO rapocore_author VALUES ("5","Amy","Tan","","Before database");;
INSERT INTO rapocore_author VALUES ("6","Andre","Agassi","","Before database");;
INSERT INTO rapocore_author VALUES ("7","Anita","Amirrezvani","","Before database");;
INSERT INTO rapocore_author VALUES ("8","Anton Joe","prakash","","Before database");;
INSERT INTO rapocore_author VALUES ("9","APJ Abdul","Kalam","","Before database");;
INSERT INTO rapocore_author VALUES ("10","Arthur C","Clarke","","Before database");;
INSERT INTO rapocore_author VALUES ("11","Arvind","Adiga","","Before database");;
INSERT INTO rapocore_author VALUES ("12","Ashwini","Sanghi","","Before database");;
INSERT INTO rapocore_author VALUES ("13","Ayn","Rand","","Before database");;
INSERT INTO rapocore_author VALUES ("14","Bachi","Karkaria","","Before database");;
INSERT INTO rapocore_author VALUES ("15","#","Balasubramaniam","","Before database");;
INSERT INTO rapocore_author VALUES ("16","Bill","Bryson","","Before database");;
INSERT INTO rapocore_author VALUES ("17","Bill","Cosby","","Before database");;
INSERT INTO rapocore_author VALUES ("18","Bishwanath","Ghosh","","Before database");;
INSERT INTO rapocore_author VALUES ("19","Chandru","Bhojwani","","Before database");;
INSERT INTO rapocore_author VALUES ("20","Chetan","Bhagat","","Before database");;
INSERT INTO rapocore_author VALUES ("21","Christine","Bailey","","Before database");;
INSERT INTO rapocore_author VALUES ("22","Edited","Collection","","Before database");;
INSERT INTO rapocore_author VALUES ("23","Dale","Carnegie","","Before database");;
INSERT INTO rapocore_author VALUES ("24","Dan","Brown","","Before database");;
INSERT INTO rapocore_author VALUES ("25","Danielle","Steel","","Before database");;
INSERT INTO rapocore_author VALUES ("26","Daphne Du","Maurier","","Before database");;
INSERT INTO rapocore_author VALUES ("27","David","Wise","","Before database");;
INSERT INTO rapocore_author VALUES ("28","Deborah","R","","Before database");;
INSERT INTO rapocore_author VALUES ("29","Devadutt","Pattanaik","","Before database");;
INSERT INTO rapocore_author VALUES ("30","Dr Spencer","Johnson","","Before database");;
INSERT INTO rapocore_author VALUES ("31","Earl Stanley","Gardner","","Before database");;
INSERT INTO rapocore_author VALUES ("32","Editors Prevention","Magazine","","Before database");;
INSERT INTO rapocore_author VALUES ("33","Edward de","Bono","","Before database");;
INSERT INTO rapocore_author VALUES ("34","Eliyahu M.","Goldratt","","Before database");;
INSERT INTO rapocore_author VALUES ("35","E. R.","Braithwhite","","Before database");;
INSERT INTO rapocore_author VALUES ("36","Er.M.K.","Gupta","","Before database");;
INSERT INTO rapocore_author VALUES ("37","Frederick","Forsyth","","Before database");;
INSERT INTO rapocore_author VALUES ("38","F. Scott","Fitzgerald","","Before database");;
INSERT INTO rapocore_author VALUES ("39","George Bernard","Shaw","","Before database");;
INSERT INTO rapocore_author VALUES ("40","Gerald I.","Nierenberg","","Before database");;
INSERT INTO rapocore_author VALUES ("41","Grace","James","","Before database");;
INSERT INTO rapocore_author VALUES ("42","Harold","Robbins","","Before database");;
INSERT INTO rapocore_author VALUES ("43","Helen","Keller","","Before database");;
INSERT INTO rapocore_author VALUES ("44","#Henry","Charriere","","Before database");;
INSERT INTO rapocore_author VALUES ("45","Hugh","Prather","","Before database");;
INSERT INTO rapocore_author VALUES ("46","Ian","Rankin","","Before database");;
INSERT INTO rapocore_author VALUES ("47","Jack","Canfield","","Before database");;
INSERT INTO rapocore_author VALUES ("48","Jack","Higgins","","Before database");;
INSERT INTO rapocore_author VALUES ("49","Jack","Krakauer","","Before database");;
INSERT INTO rapocore_author VALUES ("50","James","Patterson","","Before database");;
INSERT INTO rapocore_author VALUES ("51","Jane","Austen","","Before database");;
INSERT INTO rapocore_author VALUES ("52","Jasper","Bengtsson","","Before database");;
INSERT INTO rapocore_author VALUES ("53","Jayanand","Ukey","","Before database");;
INSERT INTO rapocore_author VALUES ("54","J D","Salinger","","Before database");;
INSERT INTO rapocore_author VALUES ("55","Jeffrey","Archer","","Before database");;
INSERT INTO rapocore_author VALUES ("56","Jesse","Jones","","Before database");;
INSERT INTO rapocore_author VALUES ("57","Jhumpa","Lahari","","Before database");;
INSERT INTO rapocore_author VALUES ("58","John","Battelle","","Before database");;
INSERT INTO rapocore_author VALUES ("59","John","Gray","","Before database");;
INSERT INTO rapocore_author VALUES ("60","John","Grisham","","Before database");;
INSERT INTO rapocore_author VALUES ("61","John Kennedy","Toole","","Before database");;
INSERT INTO rapocore_author VALUES ("62","John","Woodrof","","Before database");;
INSERT INTO rapocore_author VALUES ("63","Julie","Powell","","Before database");;
INSERT INTO rapocore_author VALUES ("64","Katherine","Boo","","Before database");;
INSERT INTO rapocore_author VALUES ("65","Kavita","Daswani","","Before database");;
INSERT INTO rapocore_author VALUES ("66","Ken","Follett","","Before database");;
INSERT INTO rapocore_author VALUES ("67","Kenneth","Blanchard","","Before database");;
INSERT INTO rapocore_author VALUES ("68","Spencer","Johnson","","Before database");;
INSERT INTO rapocore_author VALUES ("69","Khaled","Hosseini","","Before database");;
INSERT INTO rapocore_author VALUES ("70","Khalil","Gibran","","Before database");;
INSERT INTO rapocore_author VALUES ("71","Khushwant","Singh","","Before database");;
INSERT INTO rapocore_author VALUES ("72","Kiran","Bedi","","Before database");;
INSERT INTO rapocore_author VALUES ("73","Kiran","Desai","","Before database");;
INSERT INTO rapocore_author VALUES ("74","Krishnamurthy Kalki","R.","","Before database");;
INSERT INTO rapocore_author VALUES ("75","Lee","child","","Before database");;
INSERT INTO rapocore_author VALUES ("76","Madhumita","Mukherjee","","Before database");;
INSERT INTO rapocore_author VALUES ("77","Mahasweta","Devi","","Before database");;
INSERT INTO rapocore_author VALUES ("78","Malay","Chaudhari","","Before database");;
INSERT INTO rapocore_author VALUES ("79","Malcolm","Gladwell","","Before database");;
INSERT INTO rapocore_author VALUES ("80","Mani","Bhaumick","","Before database");;
INSERT INTO rapocore_author VALUES ("81","Manoj","BS","","Before database");;
INSERT INTO rapocore_author VALUES ("82","Manreet Sodhi","Someshwar","","Before database");;
INSERT INTO rapocore_author VALUES ("83","Mario","Puzo","","Before database");;
INSERT INTO rapocore_author VALUES ("84","Mark","Twain","","Before database");;
INSERT INTO rapocore_author VALUES ("85","Meghna","Pant","","Before database");;
INSERT INTO rapocore_author VALUES ("86","Michael","Crichton","","Before database");;
INSERT INTO rapocore_author VALUES ("87","M. Scott","Peck","","Before database");;
INSERT INTO rapocore_author VALUES ("88","Munshi","Premchand","","Before database");;
INSERT INTO rapocore_author VALUES ("89","Parthasarathy","Naa","","Before database");;
INSERT INTO rapocore_author VALUES ("90","Nadeem","Aslam","","Before database");;
INSERT INTO rapocore_author VALUES ("91","Nandita","Puri","","Before database");;
INSERT INTO rapocore_author VALUES ("92","Nathaniel","Hawthorne","","Before database");;
INSERT INTO rapocore_author VALUES ("93","Nicholas","Sparks","","Before database");;
INSERT INTO rapocore_author VALUES ("94","Norman VIncent","Peale","","Before database");;
INSERT INTO rapocore_author VALUES ("95","Omkar","Sane","","Before database");;
INSERT INTO rapocore_author VALUES ("96","Paramahansa","Yogananda","","Before database");;
INSERT INTO rapocore_author VALUES ("97","Patricia","Cornwell","","Before database");;
INSERT INTO rapocore_author VALUES ("98","Paulo","Coelho","","Before database");;
INSERT INTO rapocore_author VALUES ("99","Pearl S","Buck","","Before database");;
INSERT INTO rapocore_author VALUES ("100","Pratima","Mitchell","","Before database");;
INSERT INTO rapocore_author VALUES ("101","Preeti","Shenoy","","Before database");;
INSERT INTO rapocore_author VALUES ("102","#","PremChannd","","Before database");;
INSERT INTO rapocore_author VALUES ("103","Radika","Ramnath","","Before database");;
INSERT INTO rapocore_author VALUES ("104","Raghav","Bahl","","Before database");;
INSERT INTO rapocore_author VALUES ("105","Rahul","Sankrityayan","","Before database");;
INSERT INTO rapocore_author VALUES ("106","Rahul","Sankrutya","","Before database");;
INSERT INTO rapocore_author VALUES ("107","Raj","Bapna","","Before database");;
INSERT INTO rapocore_author VALUES ("108","R.","Guha","","Before database");;
INSERT INTO rapocore_author VALUES ("109","Richard","Bach","","Before database");;
INSERT INTO rapocore_author VALUES ("110","Richard","Branson","","Before database");;
INSERT INTO rapocore_author VALUES ("111","Richard","Dawkins","","Before database");;
INSERT INTO rapocore_author VALUES ("112","Robert","Ludlum","","Before database");;
INSERT INTO rapocore_author VALUES ("113","Robert T.","Kiyoski","","Before database");;
INSERT INTO rapocore_author VALUES ("114","Robin","Cook","","Before database");;
INSERT INTO rapocore_author VALUES ("115","Robin","Sharma","","Before database");;
INSERT INTO rapocore_author VALUES ("116","Rohini","Singh","","Before database");;
INSERT INTO rapocore_author VALUES ("117","Rose","Melikan","","Before database");;
INSERT INTO rapocore_author VALUES ("118","#","Saavi","","Before database");;
INSERT INTO rapocore_author VALUES ("119","Sagarika","Chakraborty","","Before database");;
INSERT INTO rapocore_author VALUES ("120","Salman","Rushdie","","Before database");;
INSERT INTO rapocore_author VALUES ("121","Shashi","Deshpande","","Before database");;
INSERT INTO rapocore_author VALUES ("122","Sheila","Hailey","","Before database");;
INSERT INTO rapocore_author VALUES ("123","Siddhartha","Mukherjee","","Before database");;
INSERT INTO rapocore_author VALUES ("124","Sidin","Vadukut","","Before database");;
INSERT INTO rapocore_author VALUES ("125","Sidney","Sheldon","","Before database");;
INSERT INTO rapocore_author VALUES ("126","Somerset","Maugham","","Before database");;
INSERT INTO rapocore_author VALUES ("127","Srini","Chandra","","Before database");;
INSERT INTO rapocore_author VALUES ("128","Srividya","Natarajan","","Before database");;
INSERT INTO rapocore_author VALUES ("129","S.R.","Luis","","Before database");;
INSERT INTO rapocore_author VALUES ("130","Stephen","Covey","","Before database");;
INSERT INTO rapocore_author VALUES ("131","Stephen","King","","Before database");;
INSERT INTO rapocore_author VALUES ("132","Steve","Martini","","Before database");;
INSERT INTO rapocore_author VALUES ("133","Stieg","Larsson","","Before database");;
INSERT INTO rapocore_author VALUES ("134","Subrato","Bagchi","","Before database");;
INSERT INTO rapocore_author VALUES ("135","Sudha","Murty","","Before database");;
INSERT INTO rapocore_author VALUES ("136","Sue","Grafton","","Before database");;
INSERT INTO rapocore_author VALUES ("137","Sumrit","Shahi","","Before database");;
INSERT INTO rapocore_author VALUES ("138","Swami Niranjananda","Saraswati","","Before database");;
INSERT INTO rapocore_author VALUES ("139","Tasleema","Nasreen","","Before database");;
INSERT INTO rapocore_author VALUES ("140","Terry","McMillan","","Before database");;
INSERT INTO rapocore_author VALUES ("141","Tina","Konstant","","Before database");;
INSERT INTO rapocore_author VALUES ("142","Urmila","Shastri","","Before database");;
INSERT INTO rapocore_author VALUES ("143","Varun","Agarwal","","Before database");;
INSERT INTO rapocore_author VALUES ("144","Vishwanath","Tiwari","","Before database");;
INSERT INTO rapocore_author VALUES ("145","Vladimir","Nabokov","","Before database");;
INSERT INTO rapocore_author VALUES ("146","William","Godman","","Before database");;
